# Generated by Django 4.1.5 on 2023-04-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Electricity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Painel',
            new_name='Inversor',
        ),
        migrations.RenameModel(
            old_name='Resultado',
            new_name='Medida',
        ),
        migrations.RenameField(
            model_name='inversor',
            old_name='numero',
            new_name='number',
        ),
    ]
