# Generated by Django 4.1.5 on 2023-04-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electricity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custo_por_kwh', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
