# Generated by Django 4.1.5 on 2023-04-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electricity', '0002_energia'),
    ]

    operations = [
        migrations.AddField(
            model_name='energia',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
